services:
  api_github:
    image: ghcr.nju.edu.cn/danny-avila/librechat-dev:latest
    volumes:
      - .:/app
    networks:
      - librechat_default

  gallery-scheduler:
    image: ghcr.nju.edu.cn/danny-avila/librechat-dev:latest
    command: ["node", "api/schedulers/galleryScheduler.js"]
    restart: always
    volumes:
      - .:/app
    networks:
      - librechat_default

networks:
  librechat_default:
    external: true